#spring:
#  datasource:
#    url: jdbc:mariadb://192.168.0.144:3307/db_odd_adv_2?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
#    username: odd_adv_2
#    password: index502
#
#  jpa:
#    show-sql: false
#    database: mysql
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        show_sql: false
#        jdbc:
#          batch_size: 1000
#        format_sql: true
#        order_inserts: true
#        order_updates: true
#
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: mappers/**/*.xml
#
#logging:
#  level:
#    org.hibernate.SQL: OFF
#    org.hibernate.type.descriptor.sql: OFF





spring:
  datasource:
    url: jdbc:mariadb://192.168.0.93:3307/db_odd_adv_2?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: odd_adv_2
    password: index502

  jpa:
    show-sql: false
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        jdbc:
          batch_size: 1000
        format_sql: true
        order_inserts: true
        order_updates: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql: OFF
