spring:
  datasource:
    url: jdbc:mariadb://112.222.157.157:5298/db_odd_adv_2
    username: odd_adv_2
    password: index502

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml

  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        format_sql: true
        order_updates: true